dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: eYIe4kNqdyhNKKkxTBYmzA0yiFG1Bv7A1HW5XckgkVv/9jUg+vxUPGIwzM2MrgjLksJK2fiud3Fbm3VfAG+T+9NVzzKDo7u8cAwknL1GJqTBEh9OCWLUSheKO0Agk+d/Esj1mD1DdSTexip1a3UtwHDyj95deFgf5hYD8m6zAX5ih2m4goqjVRBS8HxguI2yaeF4urq+Ut+mBAGpveRDDdzuRGV4GBokQCvR56UAF098CsJVvvVeLjqbidBjtt2UBJyAVUIJTSlP9iWyPf1P6RwT1HUYxISsc8pwCgBFjd3v3wC0i0hqq1AgXE76ugQoM4deXJHbqAf9oSVuBIo9IdWmVf8fvr3t6X43S+eRzMKxfOlo96PPy3CsxioJ+XJ6zowyL1l7coNSh3J/FKb57bbh2OpTRmvJgWUXYISuDKK8ccLDjOVHdtiM18Gj7PQA+5og0Xv3PB8uVhNucKXqJQSHZSTtR4+zForTqeXy+PWHzVw5se3esp9Nox9QdRR2uTFD6dKTOYGvdpcL0rH2RMAI5Z+3EzTmChWCeGjjhJifunsCrNHvI/fiMMOoLU26yQsC18iFCnRpbNC/sdErDeMrDkmnldTk2hML8I/bSXqCgVrhlM1kNTDolYPJ2moqaxVRY15BpPtDgREjcApHSk7Xxx3EHMkPHs+M9ojCaY4=
