dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: Mgs6azrCELnXXzeSzfSh3Xcv5dpB4mwV+MkWfH3ZRfml/SciPoGnYrGJMjH87KdlQePbmffDKcEcDed5dfTSpiGPx/l3cmgClfgSrKcu+u7p1t5mfAOTbby1CuwScSyKCUScrdUrgw6oLsJXwLPBxrnngS4PZqPid9MwNNcKAQqZNDUqDd5NTeQPSR3MFYUF+CvgIgXIK0Ou7xSWoMcTnZMWERUvHP+/CWeeNb6YhwEF3/R8R9hGaHoJlcSf+/gW6n9CXKgwYRux+tx9Tn6/pntoHRwo0VXO2ZmsY6KTT4HELNiub2JexXGnsZxRPhC0XFD3cUkIaThWFG8wdYnbsYZV8bHE2KJHZVXD04imRaHZJ4Vru1vRvuQRyDCB5YZfjw9gKPs/4GNb7wupchfrs0o/0/AX0xPHguVED17m0wJj5YARcw4a5j2irBpaMPUz0eiOMbY8eFZXd8MXZkK/kXqlPJT5zD/A/R/8kp8GYCVqbGbnYwfiqER+hyp5yzHIpJwi1aVBHwtRpRyw1g/UcUvk/hkbtWjngj3IWPMMzpzbydeKUT8/tHxQTaV4ssfhG0vj3slO2bP9Oo8Wr5oBJOwEXUmbxk/a99d0061xN3Oo7KSXb79f+w7lDRLgTAJ8b7kMjejJt6gGtLG5IpPfj4/BCowr7hXdwNjkRa7tutY=
