---
- name: Install Ruby, Bundler, Essential
  apt:
    update_cache: yes
    name:
      - ruby-full
      - ruby-bundler
      - build-essential
    state: present
    update_cache: yes
  tags: ruby
